import type { Metadata } from 'next'
import {  MuseoModerno } from 'next/font/google'
import './globals.css'
import './index.css'
import Navbar from './Navbar'

const museo = MuseoModerno({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${museo.className} pt-12`}>
      <Navbar />
        {children}
        </body>
    </html>
  )
}
